Multi-Language Support
kolbytn/mindcraft pull request #165
Opened 2024-08-25 21:15 UTC by FantomWolf182

Basically the bot can now chat in any language that is on Google Translate. 

The "preferred_language" property accepts a language code or name. Since it's using Google Translate names need to be formatted like on Google Translate. For example if you would like to use Chinese, "preferred_language" would have to be set to "Chinese (Simplified)" or "Chinese (Traditional)" (not case sensitive). Anything the user chat's to the bot is automatically translated to English as I didn't want the AI to bug out. The AI response is then translated to the preferred language the user stated. In case the translation fails, it responds in English. 

### Some examples:

![Screenshot 2024-08-25 160848](https://github.com/user-attachments/assets/5ee08232-204d-4aa0-9d2b-0a353a3f2010)
![image](https://github.com/user-attachments/assets/a03b0401-f0e6-4f10-9a8b-fd3e29d82402)
![image](https://github.com/user-attachments/assets/e34236f9-132b-46cf-8ee2-82ea6118144c)

2024-08-26 01:44 UTC, FantomWolf182 commented
There are still some changes that need to be made. 

Mainly if the preferred language is set to English, it shouldn't translate because the ai responds in English anyways.

2024-08-28 23:41 UTC, MaxRobinsonTheGreat requested changes
got some work for ya!

2024-08-28 23:41 UTC, MaxRobinsonTheGreat commented on settings.js
> +    "preferred_language": "english", // the bot will respond/message in this language. Secondly all language names are based on google translate's names.
can you just call it 'language'?

2024-08-28 23:41 UTC, MaxRobinsonTheGreat commented on settings.js
> +    "host": "localhost", // or "localhost", "your.ip.address.here"
remove all changes to settings.js besides language

2024-08-28 23:41 UTC, MaxRobinsonTheGreat commented on src/agent/agent.js
> +                var translation = await this.handleTranslation(message, "en");
use `let` instead of `var` everywhere

2024-08-28 23:41 UTC, MaxRobinsonTheGreat commented on src/agent/modes.js
> +async function handleTranslation(message, lang) {
this is a duplicate function, it should reuse a function from a shared translator file

2024-08-28 23:41 UTC, MaxRobinsonTheGreat commented on src/agent/agent.js
> +    async handleTranslation(message, lang) {
handleTranslation should be in its own file, `translator.js` maybe, and be imported where needed.
You shouldn't have to pass prefered_language to it, it should know by reading settings what language to translate to. maybe have a separate function to translate specifically to english

2024-08-28 23:41 UTC, MaxRobinsonTheGreat commented on src/agent/agent.js
> +		print(translation)
this should be removed (print doesn't do anything)

2024-08-28 23:41 UTC, MaxRobinsonTheGreat commented on src/agent/commands/actions.js
> +    name: '!setPreferredLanguage',
I don't like writing to the settings file at runtime. This should just change the language for the current session

2024-08-30 00:53 UTC, FantomWolf182 commented
Ok so a quick update: 

Most of the changes requested have been done. There is a translator.js file which contains everything needed to translate messages, and it's functions are called from the file where necessary. Currently the only thing that has not returned is the in-game command. This is because I can't find a straightforward way in js to update the variable in translator.js from action in actions.js

2024-09-19 02:30 UTC, FantomWolf182 commented
It's been a while but I might take a shot at this again

2024-09-28 01:45 UTC, MaxRobinsonTheGreat commented
@FantomWolf182 Hey thanks for doing all this, it is looking much better. I will test within a week.

Is the google translate api free? I can't imagine it is. Do you have to set up something to get access or does this just work?

2024-09-28 02:59 UTC, FantomWolf182 commented
yeah its completely free and just works. 

Here is the repo for it: https://github.com/AidanWelch/google-translate-api

2024-09-28 22:46 UTC, FantomWolf182 commented
The only thing missing right now is the command in game to change the preferred language. However, I wasn't able to rewrite that code to meet your revision, so I'm going to leave it out for now. Everything else should work perfectly.

2024-10-02 06:10 UTC, merged

2024-10-02 06:13 UTC, MaxRobinsonTheGreat commented
This was touched up and merged in as #205. Thank you very much @FantomWolf182, this is super useful!

2024-10-02 11:40 UTC, FantomWolf182 commented
No problem was fun to work on. Thanks for taking the time to review and merge it!