Update default embedding model to text-embedding-3-small
kolbytn/mindcraft pull request #283
Opened 2024-11-04 14:03 UTC by wlvrx

## Change Description
Updated the default embedding model for gpt from `text-ada-002` to `text-embedding-3-small`

### Rationale
- text-embedding-3-small offers better performance and is more cost-effective (5x cheaper per 1M tokens)
- I assume they're depreciating text-ada-002 sometime soon like how they did with 001

### Testing
- Verified bot functions correctly with new embedding model

2024-11-05 16:32 UTC, MaxRobinsonTheGreat requested changes
@wlvrx sorry, can you remove the attack command fix and just keep the embedding change?

I'm going to add an attackPlayer command, because your version would break if a player's name is 'zombie' or some other mob name

2024-11-06 00:05 UTC, wlvrx commented
@MaxRobinsonTheGreat Thanks for the feedback! Would you mind if I take on implementing the attackPlayer command? I can make it handle the edge case. Can submit a pr in 3 days max

2024-11-06 00:14 UTC, wlvrx commented
I've removed the attack command changes for now

2024-11-06 01:51 UTC, MaxRobinsonTheGreat commented
@wlvrx It was actually just implemented with #289 
sorry! and thanks!

2024-11-06 01:51 UTC, merged

2024-11-06 02:13 UTC, wlvrx commented
Okay! Time to find a different issue to fix lol