Use 127.0.0.1 instead of localhost to point to an IPV4 adress
kolbytn/mindcraft pull request #62
Opened 2024-04-27 09:04 UTC by Philipou

Everything is in the title :)

2024-04-27 22:31 UTC, kolbytn commented
Was this necessary because of your os?

2024-04-28 11:27 UTC, Philipou commented
Oh yes probably I did not test in linux but It may work but I think if it's set to 127.0.0.1 it will work in both i think

2024-04-29 16:24 UTC, kolbytn commented
Can you resolve the merge conflicts in local.js please.

2024-04-29 16:30 UTC, Philipou commented
Should be ok now sorry if it's not i don't do this often :)

2024-04-30 00:36 UTC, MaxRobinsonTheGreat approved these changes
looks good. @kolbytn good to merge?

2024-04-30 00:51 UTC, kolbytn requested changes

2024-04-30 00:51 UTC, kolbytn commented on src/models/local.js
> +        this.url = 'http://127.0.0.1:11434';
This needs to be `url || 'http://127.0.0.1:11434'`

2024-04-30 16:35 UTC, Philipou commented
Fixed

2024-05-04 21:27 UTC, MaxRobinsonTheGreat commented
good to merge @kolbytn?

2024-05-04 21:31 UTC, kolbytn commented
It doesn't look like @Philipou pushed his fix.

2024-05-05 20:45 UTC, Philipou commented
hmm that's weird i did fix it but i was in the bus i did it directly on my phone maybe that's the reason... welp sorry about all this mess but we have #73 now thanks ! Closing now

2024-05-05 20:45 UTC, closed without merging